import Menu from "../Menu";
import Head from 'next/head'

const Layout = ({ children }) => {
    return(
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div>
                <Menu />
                {children}
            </div>
        </>
    );
}

export default Layout;